plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
header_pages:
  - README.md
  - index.md
  - model.html
  - pipeline.md
  - results.md
  - Discussion.md

theme: minima
