plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
  - model.md
  - pipeline.md
  - results.md
  - Discussion.md

theme: jekyll-theme-dinky
