title: Deep Song Generation
theme: jekyll-theme-slate
header_pages:
  - index.md
  - pipeline.md
  - howto.md
  - preprocessing.md
  - model.md
  - results.md
  - discussion.md
  - presentation.md
